### ISSUE TITLE
Sept 13th Workshop: CEL-28 added countermeasure

### ISSUE THREAD

**Issue by sdog-mitre** [usnistgov/mobile-threat-catalogue#11]
## General Comment

**Threat ID**:
CEL-28

**Type of Comment**:
Enter the letter that best describes the nature of your comment
- T - Technical

**Proposed Change**:
Mention that some cellular carriers may offer additional encryption services that would counter eavesdropping of the backhaul.

**Justification**:
Improved completeness of countermeasures.

**Comment by sdog-nist** [comment]
Issue resolved by #110
