### ISSUE TITLE
12-2-2016 Team Meeting Outcome - Add Privacy Category

### ISSUE THREAD

**Issue by cjb9** [usnistgov/mobile-threat-catalogue#131]
General Comment
------------------------------------------
Threat ID:

Type of Comment:
G

Proposed Change:
Add a category from Privacy based threats in preparation for the next phase of the MDS project. 

Justification:
Privacy issues will be an ongoing focus of the MDS project.

**Comment by cjb9** [comment]
@mrdrewkeller is it possible to create and hide temporarily?

**Comment by mrdrewkeller** [comment]
@cjb9 It's pretty easy to add a category. I can just commit it to a branch, and then we can merge it in whenever you're ready for it to show up.

**Comment by mrdrewkeller** [comment]
When privacy threats are ready to be added, place them in the ``_privacy-threats`` folder and merge this branch ``enhancement-131``.

**Comment by mrdrewkeller** [comment]
Re-Opening to re-add Privacy to sidebar when ready
