### ISSUE TITLE
Sept 13th Workshop: Editorial comment

### ISSUE THREAD

**Issue by sdog-mitre** [usnistgov/mobile-threat-catalogue#18]
## General Comment

**Threat ID**:
None

**Type of Comment**:
Enter the letter that best describes the nature of your comment
- E - Editorial

**Proposed Change**:
Make sure to use the same term consistently across the document. Of note, Wi-Fi (a trademarked term) is not referred to correctly throughout the catalogue. It is also presented incorrectly as WiFi and WIFI. 

**Justification**:

**Comment by cjb9** [comment]
We will correct errors and consistency.
