### ISSUE TITLE
ECO-13 ECO-21 ECO-25 have the same title

### ISSUE THREAD

**Issue by mpeck12** [usnistgov/mobile-threat-catalogue#43]
## General Comment

**Threat ID**: ECO-13 ECO-21 ECO-25
**Type of Comment**: E
**Proposed Change**:
All 3 have the same title. However, the content of each is slightly different, so not sure what we want to do with these. Could either consolidate into 1 threat, or change the individual titles of all 3.

**Comment by sdog-mitre** [comment]
ECO-13 and -25 contain subsets of the information in ECO-21 and should be removed.
