### ISSUE TITLE
Add column for countermeasure actor. 

### ISSUE THREAD

**Issue by cjb9** [usnistgov/mobile-threat-catalogue#46]
This is in reference to #13

**Comment by cjb9** [comment]
@mrdrewkeller will investigate LOE.

**Comment by mrdrewkeller** [comment]
This feature will utilize key value pairs for the `PossibleCountermeasures` field. The Countermeasure being the key and the actor(s) being the value(s).

We will need to amend the contributing documentation and issue template to account for this new feature.
