### ISSUE TITLE
Workshop: STA-10 add additional countermeasures

### ISSUE THREAD

**Issue by mpeck12** [usnistgov/mobile-threat-catalogue#81]
## General Comment

**Threat ID**: STA-10

**Type of Comment**: T
**Proposed Change**:
add all the countermeasures from STA-0

**Justification**:
All the STA-0 countermeasures (e.g. install security patches) apply.

**Comment by jajmo** [comment]
I would say there's enough in STA-10 (now SPC-12) to cover all the bases. Closing.
